### ISSUE TITLE
Blank slate design

### ISSUE THREAD

**Issue by iamricard** [kristiankyvik/quizzapp#1]
So I just checked out the blank slate of your app and it looks like that. Maybe try to give it a different look? Good job otherwise!

![screenshot from 2014-08-23 11 54 27](https://cloud.githubusercontent.com/assets/3116474/4020227/a20b7ab2-2aab-11e4-9a9c-a03f1dc82565.png)

**Comment by kristiankyvik** [comment]
hahah good one

**Comment by kristiankyvik** [comment]
haha

**Comment by kristiankyvik** [comment]
hahaha
